export const TRANSACTION_CATEGORIES = [
  "Food & Dining",
  "Shopping",
  "Transportation",
  "Entertainment",
  "Bills & Utilities",
  "Healthcare",
  "Education",
  "Travel",
  "Business",
  "Personal Care",
  "Gifts & Donations",
  "Investments",
  "ATM & Banking",
  "Auto & Transport",
  "Home & Garden",
];

export const TRANSACTION_MERCHANTS = [
  "Starbucks",
  "Amazon",
  "Walmart",
  "Target",
  "McDonald's",
  "Shell",
  "Netflix",
  "Spotify",
  "Uber",
  "Lyft",
  "Apple Store",
  "Google Play",
  "PayPal",
  "Venmo",
  "Square",
  "Stripe",
  "Bank of America",
  "Chase",
  "Wells Fargo",
  "CitiBank",
];

export const TRANSACTION_LOCATIONS = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
];

export const MAX_TRANSACTIONS_LIMIT = 10_000;
